### ISSUE TITLE
Release Checklist: 1.31

### ISSUE THREAD

**Issue by ReToCode** [openshift-knative/serverless-operator#2299]
# Release Checklist

## Resources
https://github.com/openshift-knative/serverless-operator/blob/main/README.md#create-a-new-version
Video from pierdipi showing the release process

## Pre-checks
- [x] Check if the OCP versions in the release-matrix match [our current CI config](https://github.com/openshift-knative/hack/tree/main/config). If not, fix the versions first
- [x] Check if there are open PRs for Serverless-Operator that need to be merged
- [x] Check with the teams if they have all the necessary patches in the dependent repositories
- [x] [Run the `validate` action in `serverless-operator` and wait for it to complete](https://github.com/openshift-knative/serverless-operator/actions/workflows/validate.yaml)
- [x] [Merge PRs created by GitHub actions](https://github.com/openshift-knative/serverless-operator/pulls/app%2Fgithub-actions)
- [x] Make sure that all builds are passing

## Cutting the new release branch
- [x] Create a new branch from `main` with the pattern `release-x.xx`
- [x] [Approve CI setup for `release-1.X` branch in `openshift/release`](https://github.com/openshift/release/pulls/serverless-qe) and wait for the PR to be merged.
- [x] [Approve PRs created by GitHub actions bot in `serverless-operator`](https://github.com/openshift-knative/serverless-operator/pulls/app%2Fgithub-actions)
- [x] Verify that [`knative-istio-authz-chart`](https://github.com/openshift-knative/knative-istio-authz-chart/branches) has a branch with the same name as the `release-1.X` branch created previously in   serverless-operator
- [x] Verify that [`knative-istio-authz-chart`'s `Chart.yaml`](https://github.com/openshift-knative/knative-istio-authz-chart/blob/main/Chart.yaml) has `version` and `appVersion` set to the next version.

### Pre-checks
- [x] Make sure that all dependent repos have a release branch for the new version and [CI set up](https://github.com/openshift-knative/hack)
- [x] Ask the respective team to make sure that all relevant OpenShift specific patches are included in the new version
- [x] Make sure that the [automated PR to point the CSV to the old branch is merged](https://github.com/openshift-knative/serverless-operator/pulls?q=is%3Apr+author%3Aapp%2Fgithub-actions+release-+is%3Aopen) like in https://github.com/openshift-knative/serverless-operator/pull/1881

### Serving Manifests
- [x] Bump versions of `serving`, `serving_artifacts_branch`, `kourier`, `net_kourier_artifacts_branch`, `net_istio` and `net_istio_artifacts_branch`  [here](https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/project.yaml#L34)
- [x] Run `make generated-files` and send a PR

### Eventing Manifests
- [x] Bump versions of `eventing*`  [here](https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/project.yaml#L34)
- [x] Run `make generated-files` and send a PR

### Operator Manifests
- [x] Bump versions of `operator`  [here](https://github.com/openshift-knative/serverless-operator/blob/main/olm-catalog/serverless-operator/project.yaml#L34)
- [x] Run `make generated-files` and send a PR (like [this](https://github.com/openshift-knative/serverless-operator/pull/2177) for 1.10)

### Bump all golang deps
- [x] Update all versions  [here](https://github.com/openshift-knative/serverless-operator/blob/main/hack/update-deps.sh#L18)
- [x] Run `./hack/update-deps.sh --upgrade`
- [x] Run `make generated-files`
- [x] Send a PR with the changes
- [x] Pray that it works 😸  Otherwise try bump in steps and/or find a dependency version mix (with `go mod replace`) that works

## Post-release
- [x] Set CI to the new S-O branch in Eventing, [like here](https://github.com/openshift-knative/eventing/pull/3)
- [x] Set CI to the new S-O branch in Eventing Kafka Broker, [like here](https://github.com/openshift-knative/eventing-kafka-broker/pull/521/files)

**Comment by skonto** [comment]
For the openshift release repo we could have this [url](https://github.com/search?q=repo%3Aopenshift%2Frelease+Initialize+Serverless+Operator+CI+config&type=pullrequests). Are you planning to create a custom github template for this?

**Comment by ReToCode** [comment]
I changed it to https://github.com/openshift/release/pulls/serverless-qe (then we only see the open ones).

> Are you planning to create a custom github template for this?

Yes that was the idea, if its ok here, we can copy it as a template to the repo.

**Comment by skonto** [comment]
For bumping the operator here is the last link: https://github.com/openshift-knative/serverless-operator/pull/2177. We might add it as an example link instead.

**Comment by ReToCode** [comment]
I'm not sure how much that helps. I think its more important to know what to change and do than the actual PR diff.

Also the actual diff is different for each version (Serving for example now drops domain-mapping, which will not be there in the next release).

**Comment by ReToCode** [comment]
Release 1.31 is completed
