### ISSUE TITLE
Umbrella issue for having Kafka components

### ISSUE THREAD

**Issue by aliok** [openshift-knative/serverless-operator#486]
- [x] Create Kafka types: https://github.com/openshift-knative/serverless-operator/pull/472
- [x] Install Kafka components blindly (no namespace transforms, no owner refs, etc): https://github.com/openshift-knative/serverless-operator/pull/487
- [x] Set ownerRefs on channel resources which are in the same namespace, but not for KafkaSource resources which are in different namespace: https://github.com/openshift-knative/serverless-operator/pull/491
- [x] Set finalizer to be able to manually delete resources in other namespaces (knative-sources) as well as cluster scoped resources. Delete everything from manifest manually.: https://github.com/openshift-knative/serverless-operator/pull/493
- [x] Implement watching secondary resources for proper reconciliation: https://github.com/openshift-knative/serverless-operator/pull/496 AND https://github.com/openshift-knative/serverless-operator/pull/513
- [x] DeploymentsAvailable condition: https://github.com/openshift-knative/serverless-operator/pull/500
- [x] Remove the components when `spec.channel.enabled=false` or `spec.source.enabled=false`: https://github.com/openshift-knative/serverless-operator/pull/502
- [x] Use the `spec.channel.bootstrapservers` field in the spec to configure the relevant configmap: https://github.com/openshift-knative/serverless-operator/pull/503
- [x] Defaulting / requiredness check: https://github.com/openshift-knative/serverless-operator/pull/510
  - IMO it is better if `spec.channel.enabled` and `spec.source.enabled` are required.
  - Defaulting those to `true` doesn't make sense that much because need to specify the Kafka bootstrapServers for KafkaChannel.
  - Defaulting those to `false` doesn't bring any value
  - `spec.channel.bootstrapServers` needs to be required only when `spec.channel.enabled` is `true`
- [x] Use midstream manifest (probe changes, our images, etc.) --> probably needs a new patch release
  1. Need new src image for eventing-contrib (used in s-o e2e tests)
  2. Need new release yaml --> gonna copy & paste over to s-o
  3. Another thing: we need to separate the release YAML into 2 pieces for channel and source (becauce we now install these separately in s-o) --> created https://issues.redhat.com/browse/SRVKE-595
- [x] Remove configmaps from manifest that are already in eventing OR implement a transformer to remove them from manifest (so that we can use the upstream manifest as is) UPDATE: remove from manifest manually, but have a test that fails when it `tracing-config` is in manifest: https://github.com/openshift-knative/serverless-operator/pull/536
  - UPDATE: need to remove all other `config-blah`
- [x] Big PR: https://github.com/openshift-knative/serverless-operator/pull/587
  - Enable the controller
  - Add deployment shape tests
  - Adapt tooling to install and test Kafka stuff
  - Adapt CSV and CSV related scripts
- [x] Implement image override to be able to override images with productized ones: https://github.com/openshift-knative/serverless-operator/pull/594
- [x] Make things are installed in `knative-eventing` namespace only: https://github.com/openshift-knative/serverless-operator/pull/605
- [x] Manifest apply/delete improvements: https://github.com/openshift-knative/serverless-operator/pull/606
  - Apply roles and clusterRoles first
  - Don't delete CRDs
- [x] Downstream smoke tests: https://github.com/openshift-knative/serverless-operator/pull/595
- [x] Use CRD v1 API: https://github.com/openshift-knative/serverless-operator/pull/607
- [x] Enable eventing-contrib upstream tests: https://github.com/openshift-knative/serverless-operator/pull/620

Non-critical:

- [x] Enable Prometheus gauges again --> dashboard is not set up to use these gauges: https://github.com/openshift-knative/serverless-operator/pull/618
- [x] Does the test to check if we have any `gcr.io` images enabled for KnativeKafka stuff?
- [x] Printer columns adjustment for the CRD: https://issues.redhat.com/browse/SRVKE-569
- [x] Version info in the status --> we won't do this: https://github.com/openshift-knative/serverless-operator/pull/609
- [x] Check if eventing is installed first: https://issues.redhat.com/browse/SRVKE-572
- [x] Think about the secondary resource watching: https://github.com/openshift-knative/serverless-operator/pull/496#pullrequestreview-503572599 --> left it to Markus
- [x] Create ticket for future improvements
  - Get rid of manifest merging function when Manifestival is upgraded to 0.6.x (that version has that functionality) --> no need for a ticket. There's a TODO in the code
  - Create additional smaller interfaces in upstream for `KComponent`, `KComponentSpec`, etc. so that some functions in the upstream are also applicable to `KnativeKafka`, `KnativeKafkaSpec`, etc. --> Won't do this for now. We can do it much later but no need for a ticket.
  - ...

Things I noticed:
- No upgrade tests for eventing in s-o
- No controller unit tests for eventing in s-o
- Another thing: we need to separate the release YAML into 2 pieces for channel and source (becauce we now install these separately in s-o) in midstream eventing-contrib --> created https://issues.redhat.com/browse/SRVKE-595

**Comment by aliok** [comment]
Notes:
- Apply roles and clusterRoles first
- Don't delete CRDs
